// 搜索引擎
// 0 百度
// 1 多吉
// 2 必应
// 3 搜狗
// 4 360
// 5 谷歌
// 6 bilibili
// 7 淘宝
// 8 京东
// 9 腾讯视频
// 10 AcFun
// 11 Iconfont
// 12 Yandex
// 13 CSDN
// 14 GitHub
// 15 百度百科

// const engines = [{
//     title: "百度",
//     url: "http://www.baidu.com/s",
//     name: "wd"
// }, {
//     title: "多吉搜索",
//     url: "https://www.dogedoge.com/results",
//     name: "q"
// }, {
//     title: "必应",
//     url: "https://cn.bing.com/search",
//     name: "q"
// }, {
//     title: "搜狗",
//     url: "https://www.sogou.com/sogou",
//     name: "query"
// }, {
//     title: "360",
//     url: "https://www.so.com/s",
//     name: "q"
// }, {
//     title: "谷歌",
//     url: "https://www.google.com/search",
//     name: "q"
// }, {
//     title: "bilibili",
//     url: "https://search.bilibili.com/all",
//     name: "keyword"
// }, {
//     title: "淘宝",
//     url: "https://s.taobao.com/search",
//     name: "q"
// }, {
//     title: "京东",
//     url: "https://search.jd.com/Search",
//     name: "keyword"
// }, {
//     title: "腾讯视频",
//     url: "https://v.qq.com/x/search/",
//     name: "q"
// }, {
//     title: "AcFun",
//     url: "https://www.acfun.cn/search",
//     name: "keyword"
// }, {
//     title: "Iconfont",
//     url: "https://www.iconfont.cn/search/index",
//     name: "q"
// }, {
//     title: "Yandex",
//     url: "https://yandex.com/search/",
//     name: "text"
// }, {
//     title: "CSDN",
//     url: "https://so.csdn.net/so/search/s.do",
//     name: "q"
// }, {
//     title: "GitHub",
//     url: "https://github.com/search",
//     name: "q"
// }, {
//     title: "百度百科",
//     url: "https://baike.baidu.com/search",
//     name: "word"
// }
// ];
